db.peliculas.insertMany([
    {pelicula:"Spider-Man lejos de casa",genero:"ficcion", estrellas:5},
    {pelicula:"Venom",genero:"ficcion", estrellas:4.5}, 
    {pelicula:"Sin tiempo para morir",genero:"drama", estrellas:4.25},
    {pelicula:"La familia Addamas",genero:"comedia", estrellas:3.25},
    {pelicula:"Madres paralelas",genero:"drama", estrellas:4},
    {pelicula:"Las elites de la costa",genero:"comedia", estrellas:3},
    {pelicula:"Familiars",genero:"terror", estrellas:4.5},
    {pelicula:"Burial Ground Massacre",genero:"terror", estrellas:5},
    {pelicula:"Shang-Chi",genero:"accion", estrellas:4.75},
    {pelicula:"Bruto vs Cesar",genero:"Comedia", estrellas:1},
    {pelicula:"Hunters",genero:"accion", estrellas:5},
    {pelicula:"Injustice",genero:"accion", estrellas:2},
    {pelicula:"Megalodon",genero:"terror", estrellas:3.5},
    {pelicula:"Kilit",genero:"suspense", estrellas:1.5},
    {pelicula:"Black Site",genero:"Suspense", estrellas:4},
    {pelicula:"Final Kill",genero:"suspense", estrellas:3.75},
    {pelicula:"Dune",genero:"accion", estrellas:4.75},
    {pelicula:"The Eight Hundred",genero:"suspense", estrellas:5},
    {pelicula:"Most Dangerous Game",genero:"accion", estrellas:4},
])